### PR TITLE
Flutter file examples apart from image

### PR DESCRIPTION
**Pull request by lohanidamodar**
```dart
// generated code
import 'package:appwrite/appwrite.dart';

void main() { // Init SDK
  Client client = Client();
  Storage storage = Storage(client);

  client
    .setEndpoint('https://[HOSTNAME_OR_IP]/v1') // Your API Endpoint
    .setProject('5df5acd0d48c2') // Your project ID
  ;
  // downloading file
  Future result = storage.getFileDownload(
    bucketId: '[BUCKET_ID]',
    fileId: '[FILE_ID]',
  ).then((bytes) {
    final file = File('path_to/file.pdf');
    file.writeAsBytesSync(bytes)
  }).catchError((error) {
      print(error.response);
  })
}

//displaying image preview
FutureBuilder(
  future: storage.getFileDownload(
    bucketId: '[BUCKET_ID]',
    fileId: '[FILE_ID]',
  ), //works for both public file and private file, for private files you need to be logged in
  builder: (context, snapshot) {
    return snapshot.hasData && snapshot.data != null
      ? Image.memory(
          snapshot.data,
        )
      : CircularProgressIndicator();
  },
);

```

### CODE REVIEW

**Review by gewenyu99 — APPROVED** [review]
LGTM

**Comment by gewenyu99** [comment]
Consider not using `path_to/file.pdf` by default, idk if it's a good idea to assume its a pdf, but the example looks good :)

**Comment by lohanidamodar** [comment]
> Consider not using `path_to/file.pdf` by default, idk if it's a good idea to assume its a pdf, but the example looks good :)

is this better

```dart
// generated code
import 'package:appwrite/appwrite.dart';

void main() { // Init SDK
  Client client = Client();
  Storage storage = Storage(client);

  client
    .setEndpoint('https://[HOSTNAME_OR_IP]/v1') // Your API Endpoint
    .setProject('5df5acd0d48c2') // Your project ID
  ;
  // downloading file
  Future result = storage.getFileDownload(
    bucketId: '[BUCKET_ID]',
    fileId: '[FILE_ID]',
  ).then((bytes) {
    final file = File('path_to_file/filename.ext');
    file.writeAsBytesSync(bytes)
  }).catchError((error) {
      print(error.response);
  })
}

//displaying image preview
FutureBuilder(
  future: storage.getFileDownload(
    bucketId: '[BUCKET_ID]',
    fileId: '[FILE_ID]',
  ), //works for both public file and private file, for private files you need to be logged in
  builder: (context, snapshot) {
    return snapshot.hasData && snapshot.data != null
      ? Image.memory(
          snapshot.data,
        )
      : CircularProgressIndicator();
  },
);

```

**Comment by gewenyu99** [comment]
> > Consider not using `path_to/file.pdf` by default, idk if it's a good idea to assume its a pdf, but the example looks good :)
> 
> is this better
> 
> ```dart
> // generated code
> import 'package:appwrite/appwrite.dart';
> 
> void main() { // Init SDK
>   Client client = Client();
>   Storage storage = Storage(client);
> 
>   client
>     .setEndpoint('https://[HOSTNAME_OR_IP]/v1') // Your API Endpoint
>     .setProject('5df5acd0d48c2') // Your project ID
>   ;
>   // downloading file
>   Future result = storage.getFileDownload(
>     bucketId: '[BUCKET_ID]',
>     fileId: '[FILE_ID]',
>   ).then((bytes) {
>     final file = File('path_to_file/filename.ext');
>     file.writeAsBytesSync(bytes)
>   }).catchError((error) {
>       print(error.response);
>   })
> }
> 
> //displaying image preview
> FutureBuilder(
>   future: storage.getFileDownload(
>     bucketId: '[BUCKET_ID]',
>     fileId: '[FILE_ID]',
>   ), //works for both public file and private file, for private files you need to be logged in
>   builder: (context, snapshot) {
>     return snapshot.hasData && snapshot.data != null
>       ? Image.memory(
>           snapshot.data,
>         )
>       : CircularProgressIndicator();
>   },
> );
> ```

Yep, this looks better :D

**Review by abnegate — APPROVED** [review]
LGTM 👍

**Pull request merged**
