### PR TITLE
Added missing docs templates for Java

### PR DESCRIPTION
**Pull request by ng29**
Hi @eldadfux 

Please find PR for issue -> https://github.com/appwrite/sdk-generator/issues/42

Regards,
Nitin

### CODE REVIEW

**Comment by eldadfux** [comment]
@punitdiwan / @christyjacob4 please help validate the new Java templates 🙏🏻

**Comment by punitdiwan** [comment]
Sure I will review it.

**Review by punitdiwan — COMMENTED** [review]
Looks fine at the top. Request you @christyjacob4 can you share your thought by executing the doc generation code .

**Comment by christyjacob4** [comment]
Thanks @punitdiwan . I will take a look 👍

**Comment by eldadfux** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like me to send you some cool Appwrite stickers and magnets! Please note that shipping might take longer times because of COVID19.

As a way of saying thank you, we have just invited you to join the Appwrite organization on GitHub. You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

**Pull request merged**
