### PR TITLE
refactor: added type hints for Python SDK

### PR DESCRIPTION
**Pull request by Ananya2001-an**
## What does this PR do?

Added type hints for better readability and maintainability. It's added only for a few methods at the moment but can improve on that later on... :)

## Related PRs and Issues

With reference to issue: https://github.com/appwrite/sdk-for-python/issues/43

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Review by stnguyen90 — APPROVED** [review]

**Comment by stnguyen90** [comment]
@lohanidamodar, I think we should merge this and iterate upon it to add even more.

**Comment by lohanidamodar** [comment]
Thanks @stnguyen90.
@abnegate would love to hear your thoughts as well.

**Comment by lohanidamodar** [comment]
@Ananya2001-an would you like to continue further to add type hints for the remaining parts? If not I'll merge your PR into a separate branch so that our team can work on top of it. Let me know ho you would like to proceed.

**Comment by Ananya2001-an** [comment]
Hey @lohanidamodar I would love to continue working on it....later on you can merge it to a separate branch when I have done the final changes according to me :)

**Comment by Ananya2001-an** [comment]
Hey, I think you can merge this for now since I am not sure where to add type hints further :)

**Comment by lohanidamodar** [comment]
@Ananya2001-an not a problem. Thank you for your contribution

**Pull request merged**
