### PR TITLE
Add types declaration in JS SDK

### PR DESCRIPTION
**Pull request by zevektor**
This PR is to use the JS SDK in a TypeScript project by creating a types declaration file in the JS language itself, instead of creating a dedicated TS SDK.

Should help to solve #20

### CODE REVIEW

**Comment by eldadfux** [comment]
Thanks for the PR, is there any way I can validate the changes? How can I check it with my VS code? Do I need any plugin?

**Comment by zevektor** [comment]
Hi @eldadfux ,

To check if it works, you can:

- Compile the sdk
- Create a blank typescript project
- Add a local dependency to your package.json file: `"appwrite": "file:/path/to/js/sdk",`
- Test the SDK

Example of import:
```typescript
import Appwrite from 'appwrite';
export default class TestAppwrite {

  private static client = new Appwrite().setEndpoint('endpoint').setProject('project_id')

  public static addUser(email: string, password: string, name: string) {
    this.client.account.create(email, password, name)
  }

}
```

**Comment by eldadfux** [comment]
THANK YOU! All changes merged 🥳 
Please reach out to me on our [Discord server](https://discord.gg/GSeTUeA) if you would like me to send you some cool Appwrite stickers and magnets! (Might take a lot of time for shipping because of the global lockdown)

As a way of saying thank you, we have just invited you to join the Appwrite organization on GitHub. You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership visibility settings, so your new Appwrite team membership badge will show up on your personal GitHub profile.

**Comment by eldadfux** [comment]
@zevektor, added some minor updates and deployed a demo version here:
https://github.com/aw-tests/sdk-for-js

**Comment by eldadfux** [comment]
@zevektor this is now live in Appwrite 0.6: https://dev.to/eldadfux/appwrite-0-6-comes-with-full-typescript-support-2ff2 Thank you so much! ❤️

**Comment by eldadfux** [comment]
image

**Pull request merged**
