### PR TITLE
Feat CLI pagination

### PR DESCRIPTION
**Pull request by abnegate**
## What does this PR do?

- Add scaling timeout for attribute/index create/delete
- Add pagination

## Test Plan

Manual test + existing tests

## Related PRs and Issues

https://github.com/appwrite/appwrite/issues/6915

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Review by lohanidamodar — APPROVED** [review]
Looks good, can you share screenshot of how this works in action? @abnegate

**Comment by tripolskypetr** [comment]
@abnegate @lohanidamodar Guys what the status of that bug? Looks like this MR approved but It stuck in daily routine

**Comment by abnegate** [comment]
@lohanidamodar 
Screenshot 2023-11-15 at 17 05 06

@tripolskypetr Almost there :grin:

**Comment by lohanidamodar** [comment]
LGTM

**Pull request merged**
