### PR TITLE
Fix: CLI collection init&deploy (databases)

### PR DESCRIPTION
**Pull request by Meldiron**
## What does this PR do?

`appwrite deploy collection` did not update collection configuration (name, enabled, permissions...). Now it does.

Also removed unused import.

We also never stored database name. Only ID. We now also store and use database ID.

## Test Plan

 - [x] Manual QA

update collection settings:

https://user-images.githubusercontent.com/19310830/193419432-bd1687be-9db0-4a97-ab9c-2556ee6dec02.mp4

store database name:

https://user-images.githubusercontent.com/19310830/193419735-aabc7373-35ea-4120-9003-f2b4793b9e13.mp4

## Related PRs and Issues

x

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Review by lohanidamodar — COMMENTED** [review]
Looks good. Though is the name initCollection/deployCollection still okay? as we are also pulling and pushing databases?

**Comment by Meldiron** [comment]
@lohanidamodar I think it still makes sense for multiple reasons:
- Not introducing backward change for no reason
- Functionality barely touched. We already had to create a database when deploying collections. The only thing that changed is that we now know the database name too, instead of setting it to databaseId.

**Review by lohanidamodar — APPROVED** [review]

**Comment by johannesschobel** [comment]
love it.. highly needed.
I have 2 databases in one project to separate sensitive information. currently i can export all collections from all databases but not deploy them back to the server!

**Comment by lohanidamodar** [comment]
@Meldiron we have conflicts

**Comment by stnguyen90** [comment]
https://github.com/appwrite/sdk-for-cli/issues/47

**Comment by stnguyen90** [comment]
https://github.com/appwrite/sdk-for-cli/issues/49

**Pull request merged**
