### PR TITLE
update inputfile for dart and flutter

### PR DESCRIPTION
**Pull request by lohanidamodar**
## What does this PR do?

- Update InputFile interface

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

YES

### CODE REVIEW

**Review by gewenyu99 — APPROVED** [review]
This will still be backwards compatible right?

**Comment by gewenyu99** [comment]
When will this be released? Should we wait on: https://github.com/appwrite/docs/pull/339 until after release?

**Comment by lohanidamodar** [comment]
> This will still be backwards compatible right?

No this will be breaking change only on SDK though, do you think we should have backward compatible for this SDK only change? If yes, I can try to make it backward compatible?

**Comment by lohanidamodar** [comment]
Now it should be backward compatible, but signifying that it is deprecated, so that we can remove it in next major version release.

**Comment by gewenyu99** [comment]
> Now it should be backward compatible, but signifying that it is deprecated, so that we can remove it in next major version release.

Yeahhhhh This would be great if it's first deprecated then we can move away in the future version 👍

**Review by stnguyen90 — APPROVED** [review]

**Pull request merged**
