### PR TITLE
Upgrade `device_info_plus` and `package_info_plus`

### PR DESCRIPTION
**Pull request by nohli**
## What does this PR do?

It upgrades the `device_info_plus` and `package_info_plus` dependencies for Flutter.

Since both major versions were updated, apps can't use `appwrite` together with the latest versions of `device_info_plus` and `package_info_plus` at the moment (at least not without`dependency_overrides`).

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by nohli** [comment]
FYI there were refactorings over at `plus_plugins`, generally resulting in breaking changes.
Also, there was a [Flutter bug](https://github.com/flutter/flutter/pull/96610) affecting many users, that's why tests failed. It is fixed now.

**Comment by stnguyen90** [comment]
@nohli, would you please sync with master to fix the CI job?

**Comment by nohli** [comment]
@stnguyen90 done. Tests are passing 🙂 
Was the reason for disabling the Flutter beta test the failing `path_provider` test?

**Review by lohanidamodar — APPROVED** [review]
Looks good. Yes the reson was the failing path_provider on beta any update on that @nohli ?

**Comment by nohli** [comment]
@lohanidamodar I asked a Googler about the failing test, see the first sentence of his [answer](https://github.com/fluttercommunity/plus_plugins/issues/1226#issuecomment-1287014538).
But unsure if he only meant unit tests and not integration tests (which would make sense to test if everything works).

If you mock plugins, as described [here](https://docs.flutter.dev/development/packages-and-plugins/plugins-in-tests), you could only test the behavior of the app and not test if external plugins work (and fix tests).

Another question is if the tests of plugins are generally flaky during Flutter tests, or if there was a change/bug in Flutter beta (could perhaps be tested with Flutter master, if it's a bug it could have been fixed there).

**Pull request merged**
