### PR TITLE
Add runtime dependency mime-type to gemspec

### PR DESCRIPTION
**Pull request by foxy-eyed**
Resolves https://github.com/appwrite/sdk-generator/issues/281

### CODE REVIEW

**Comment by eldadfux** [comment]
@foxy-eyed Thank you so much for your contribution! Please sync with master. This should allow the tests to pass before we can merge this PR.

**Comment by christyjacob4** [comment]
@foxy-eyed Oops. Looks like there is a merge conflict preventing me from merging your PR. Can you please fix it

**Comment by foxy-eyed** [comment]
@christyjacob4 looks like you already merged more recent [changes](https://github.com/appwrite/sdk-generator/commit/89ee90240b1d0c6081554329117c2a9c6e9139b0#diff-b38ade45d1f8818c2c7122b87e5762f8623f4543a9953e522a4bed67b42bda34) which does the same. So there is no point to resolve this, just close.

**Comment by christyjacob4** [comment]
@foxy-eyed  Thank you for pointing it out. Closing this one 🙏  
We'd love you to explore some open [issues on Appwrite](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Aappwrite+org%3Autopia-php+no%3Aassignee)

**Pull request closed without merging**
