### PR TITLE
feat: ssr

### PR DESCRIPTION
**Pull request by loks0n**
## What does this PR do?

- Replaces node dependencies `form-data` and `axios` with `undici`.
- Drops support for Node 14 and adds Node 20

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Review by abnegate — COMMENTED** [review]
Looks good, any insight into the CLI test failures? Looks like they were passing previously but I see you haven't any of the templates there :thinking:

**Comment by loks0n** [comment]
> Looks good, any insight into the CLI test failures? Looks like they were passing previously but I see you haven't any of the templates there 🤔

Seems like something related to the qa server it's testing against. I had a go at fixing and then migrating to undici in CLI, but it's quite a bit of work so can raise a separate PR to avoid blocking SSR.

**Review by lohanidamodar — APPROVED** [review]

**Comment by lohanidamodar** [comment]
@loks0n why are we using qa.appwrite.org ? Didn't we already move all the tests to SDK generator itself? Can you check?

**Comment by lohanidamodar** [comment]
@loks0n Also, I switched the base branch, make sure you sync with this branch.

**Comment by loks0n** [comment]
> @loks0n Also, I switched the base branch, make sure you sync with this branch.

Updated

**Review by abnegate — APPROVED** [review]

**Pull request merged**
