### PR TITLE
fixing flutter web auth not finding

### PR DESCRIPTION
**Pull request by Silfalion**
this should fix flutter auth not finding the key parameter when trying to create an OAuth session

### CODE REVIEW

**Review by lohanidamodar — APPROVED** [review]

**Comment by lohanidamodar** [comment]
@Silfalion Thanks for the PR, we will fix the issue and publish soon.

**Comment by Silfalion** [comment]
Awesome, thank you for your time! And sorry for any inconvenience.

**Comment by lohanidamodar** [comment]
> Awesome, thank you for your time! And sorry for any inconvenience.

No problem. We love community contributions .

**Comment by lohanidamodar** [comment]
@Silfalion I have made certain adjustment, that i would love to release with next version, can you please sync with the new branch (https://github.com/appwrite/sdk-generator/tree/fix-flutter-exports) and update your PR.

Thanks 🙏🏻

**Comment by Silfalion** [comment]
Of course! You mean resolve the conflict, right?

**Comment by lohanidamodar** [comment]
> Of course! You mean resolve the conflict, right?
> […](#)
> On 6 Sep 2021 at 06:37 +0100, Damodar Lohani ***@***.***>, wrote: @Silfalion I have made certain adjustment, that i would love to release with next version, can you please sync with the new branch (https://github.com/appwrite/sdk-generator/tree/fix-flutter-exports) and update your PR. Thanks 🙏🏻 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes!

**Review by lohanidamodar — APPROVED** [review]
Great, thanks!

**Comment by Silfalion** [comment]
My pleasure!

**Pull request merged**
