### PR TITLE
fix-cli-code-examples

### PR DESCRIPTION
**Pull request by lohanidamodar**

### CODE REVIEW

**Review by TorstenDittmann — COMMENTED** [review]
We might run into issues here, since `\` is not supported on windows.

**Comment by lohanidamodar** [comment]
> We might run into issues here, since `\` is not supported on windows.

@eldadfux we might need separate example for windows and unix?

**Comment by eldadfux** [comment]
Still not sure how to do it, maybe we can create 2 separate folders in the CLI repo, and adjust the docs to handle multiple variations per SDK?

**Comment by eldadfux** [comment]
I would still keep the unix one as is for easier transition and just add another `examples-cmd` / `examples/powershell` examples

**Pull request merged**
