### PR TITLE
fixed: non-ASCII char in request header

### PR DESCRIPTION
**Pull request by kutear**
> Historically, HTTP has allowed field content with text in the
ISO-8859-1 charset [ISO-8859-1], supporting other charsets only
through use of [RFC2047] encoding. In practice, most HTTP header
field values use only a subset of the US-ASCII charset [USASCII].
Newly defined header fields SHOULD limit their field values to
US-ASCII octets. A recipient SHOULD treat other octets in field
content (obs-text) as opaque data.

But `appName` may be contain non-ASCII char. so replace with `package`

ref: https://github.com/appwrite/sdk-for-flutter/issues/25

### CODE REVIEW

**Review by lohanidamodar — APPROVED** [review]
Seems logical. Thank you for your PR

**Comment by lohanidamodar** [comment]
@kutear can you please sync with latest master so that we can see the tests passing. Thank you 🙏🏻

**Comment by kutear** [comment]
> @kutear can you please sync with latest master so that we can see the tests passing. Thank you 🙏🏻

I had merge `master` and ci was passed.

**Comment by eldadfux** [comment]
Thanks @kutear !

**Pull request merged**
