### PR TITLE
Feat: Improve Pub Points on `pub.dev`

### PR DESCRIPTION
**Pull request by niteshsh4rma**
## What does this PR do?

- Removed Unused Import
- Change `dart:html/html.dart` to `package:universal_html/html.dart`

## Test Plan

- Nothing major changed, no testing required

## Related PRs and Issues

- Fixes https://github.com/appwrite/sdk-for-flutter/issues/88

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by niteshsh4rma** [comment]
BSD3 "New" & "Updated" Clause License content can only be updated by the maintainers.

**Comment by stnguyen90** [comment]
@niteshsh4rma Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by lohanidamodar** [comment]
@niteshsh4rma What's the purpose of using universal_html?

**Comment by stnguyen90** [comment]
@niteshsh4rma, I know I suggested using universal_html, but we're actually a little hesitant to add another package dependency. Would you be able to see if using conditional imports/exports would pass the static analysis?

**Comment by niteshsh4rma** [comment]
@stnguyen90 sure

**Comment by niteshsh4rma** [comment]
> @niteshsh4rma, I know I suggested using universal_html, but we're actually a little hesitant to add another package dependency. Would you be able to see if using conditional imports/exports would pass the static analysis? Apologies for the inconvenience!

Tried with conditional imports, but didn't worked.

**Comment by stnguyen90** [comment]
@lohanidamodar, thoughts?

**Comment by Meldiron** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Review by lohanidamodar — APPROVED** [review]

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
