### PR TITLE
Update go client

### LINKED ISSUE #8: Add GO Templates to the SDK Generator
We need help adding GO templates to this project to allow easy generation of GO SDKs for Appwrite server.

A full guide on how to add new language support to the Appwrite SDK generator is located here:
https://github.com/appwrite/sdk-generator/blob/master/CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Suven-p**
## What does this PR do?
Adding chunking support to go SDK

Fixes #8

## Test Plan

Test storage.CreateFile and functions.CreateDeployment endpoints

## Related PRs and Issues

* #8
* https://github.com/appwrite/sdk-generator/pull/16

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by Suven-p** [comment]
@lohanidamodar This isn't complete but before I complete this could you check https://github.com/Suven-p/sdk-for-go/blob/7123c8348cb6360a0db1dfa6ba5831c5c8435579/databases/databases.go#L31 to see if it is a good idea. The usage for optional parameters is `database.List(databases.WithListQuery([queries]), databases.WithListSearch("Search term")`. This gets very verbose with 
```
WithCreateCollectionPermissions([]interface{}{
    appwrite.NewPermission().Read(appwrite.NewRole().any()),
    appwrite.NewPermission().Write(appwrite.NewRole().any())
})
``` 
and this is a single argument to CreateCollection endpoint.

**Comment by lohanidamodar** [comment]
> @lohanidamodar This isn't complete but before I complete this could you check [Suven-p/sdk-for-go@`7123c83`/databases/databases.go#L31](https://github.com/Suven-p/sdk-for-go/blob/7123c8348cb6360a0db1dfa6ba5831c5c8435579/databases/databases.go#L31) to see if it is a good idea. The usage for optional parameters is `database.List(databases.WithListQuery([queries]), databases.WithListSearch("Search term")`. This gets very verbose with
> 
> ```
> WithCreateCollectionPermissions([]interface{}{
>     appwrite.NewPermission().Read(appwrite.NewRole().any()),
>     appwrite.NewPermission().Write(appwrite.NewRole().any())
> })
> ```
> 
> and this is a single argument to CreateCollection endpoint.

@Suven-p I'm completely new to Go ecosystem and don't completely understand what do you mean. Can you share some perspective. Also we would love to keep syntax close to Platform  (i.e GO lang) standards and possibly consistent with existing SDKs whenever possible. Share some more perspective and what's the common standards of Golang, and let me know how I can help.

**Comment by Suven-p** [comment]
@lohanidamodar This should be done now. I am not sure how to test this since there are a lot of routes. Are the default tests sufficient?

For the directory structure, I am following the standard library@https://cs.opensource.google/go/go/+/refs/tags/go1.20.4:src/go.mod ie one module with many packages organized by directory.

For optional parameters, I am following [this article](https://mariocarrion.com/2021/11/05/learning-golang-functional-pattern-options-default-configuration-values.html).

**Comment by Suven-p** [comment]
The test case for last commit fails due to https://github.com/appwrite/appwrite/issues/5392

**Pull request merged**
