### PR TITLE
Update flutter code to use js_interop

### PR DESCRIPTION
**Pull request by svenopdehipt**
I update the flutter code to use the new js_interop (https://dart.dev/interop/js-interop). I did replace universal_http with package web and dart.library.html with dart.library.js_interop

### CODE REVIEW

**Comment by lohanidamodar** [comment]
@svenopdehipt Great work and thank you for the PR, please sync PR and resolve conflict and we can move forward.

**Comment by svenopdehipt** [comment]
I have rebased the branch.

**Comment by svenopdehipt** [comment]
@lohanidamodar Is there some other problem? Should I rebase it again?

**Review by lohanidamodar — APPROVED** [review]
Looks good.

**Pull request merged**
