### PR TITLE
Improving Go Templates.

### PR DESCRIPTION
**Pull request by phaus**
* Fixing #8
* Adding Support for go modules
* Using JSON Payload for Documents

### CODE REVIEW

**Comment by phaus** [comment]
Hi @eldadfux  any chance to have this merged within #hacktober? ;-)

**Comment by eldadfux** [comment]
This are the docs about the tests: https://github.com/appwrite/sdk-generator/blob/master/CONTRIBUTING.md#tests

I have also noticed, you added a cookiejar library, usually for server-side langs we don't need the cookie implementation as the only way to authenticate are with a JWT or an API key.

**Comment by phaus** [comment]
Thx. I guess, I will re-create a branch with the required changes. I have to look, when I find the time. 
Good thing is, that the updates do provide a working client :-).

**Comment by christyjacob4** [comment]
This looks great @phaus . Could you share some updates with us? Are you still working on this ?

**Comment by phaus** [comment]
Yes. I am planning to do so. I have some busy weeks at the moment. But this is still on my list.

**Comment by christyjacob4** [comment]
@phaus  Awesome no worries. Thank you for letting us know  🤩

**Comment by christyjacob4** [comment]
@phaus closing this issue for now. Please feel free to reopen it/ create a new one when you're ready to start working on it once again

**Comment by phaus** [comment]
@christyjacob4 I did update my branch and the implementation now fulfils the mock test cases (+a test of the download).
Should I create another PR or is it okay for you, to reopen this one?

**Pull request closed without merging**
