### PR TITLE
Feat Dart custom exception

### PR DESCRIPTION
**Pull request by lohanidamodar**

### CODE REVIEW

**Comment by eldadfux** [comment]
@lohanidamodar build is failing

image

**Comment by lohanidamodar** [comment]
@eldadfux the error is not related to my change, has something changed in the test spec? When I try to run test, I get following error
```
) Tests\SDKTest::testHTTPSuccess
Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("Array to string conversion").

sdk-generator/templates/dart/lib/services/service.dart.twig:5
sdk-generator/vendor/twig/twig/src/Template.php:378
sdk-generator/vendor/twig/twig/src/Template.php:390
sdk-generator/vendor/twig/twig/src/TemplateWrapper.php:45
..............
```

The `sdk-generator/templates/dart/lib/services/service.dart.twig:5` contains following 
```
{% if parameter.required %}@required {% endif %}{{ parameter.type | typeName }} {{ parameter.name | caseCamel }}{{ parameter | escapeDollarSign | paramDefault }}{% endif %}
```

When I generate package using `example.php` everything is working fine.

**Comment by eldadfux** [comment]
I didn't change anything, and latests tests are passing

**Comment by lohanidamodar** [comment]
@eldadfux I'm getting same error while trying to run tests on dart on Master branch as well ?

**Comment by lohanidamodar** [comment]
@eldadfux looks like the above error is for me only on local. 
Other error was because I forgot to add the exception file to Dart.php, which is now fixed and ready!

**Pull request merged**
