### PR TITLE
Flutter SDK Custom user agent

### PR DESCRIPTION
**Pull request by lohanidamodar**
Resolves https://github.com/appwrite/appwrite/issues/946

Preview of how createSession responds with user device details on Android

### CODE REVIEW

**Comment by eldadfux** [comment]
Hey @lohanidamodar , what about Windows, MacOS and other possible platforms?

**Comment by lohanidamodar** [comment]
> Hey @lohanidamodar , what about Windows, MacOS and other possible platforms?

Look into those as well

**Review by TorstenDittmann — APPROVED** [review]
lgtm 👍🏻 

Web is gonna be handled by the browser right? Will this impact our Pub Score?

**Comment by lohanidamodar** [comment]
> lgtm 👍🏻
> 
> Web is gonna be handled by the browser right? Will this impact our Pub Score?

Yes web is automatically handled. Shouldn't impact Pub score.

**Pull request merged**
